# Generated by Django 4.1.5 on 2023-03-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="pending_mobile",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
