# Generated by Django 4.0.1 on 2022-01-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_billingaccount_account_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_verification_code",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pending_mobile",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
