# Generated by Django 4.0.1 on 2022-06-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_mobile_user_mobile_verification_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaccount",
            name="stripe_customer_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
