# Generated by Django 4.0.1 on 2022-06-04 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_billingaccount_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="billing_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.billingaccount",
            ),
        ),
    ]
