# Generated by Django 4.0.1 on 2022-06-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_billing_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaccount",
            name="credit_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="stripe_payment_method_expires_at",
            field=models.DateTimeField(null=True),
        ),
    ]
