# Generated by Django 4.0.1 on 2022-06-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_billingaccount_credit_account_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billingaccount",
            name="stripe_payment_method_expires_at",
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="stripe_setup_intent_active",
            field=models.BooleanField(default=False),
        ),
    ]
