# Generated by Django 4.0.1 on 2022-06-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0008_remove_billingaccount_stripe_payment_method_expires_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_operator",
            field=models.BooleanField(default=False),
        ),
    ]
