# Generated by Django 4.1.3 on 2022-12-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_is_operator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="billing_account",
        ),
        migrations.DeleteModel(
            name="BillingAccount",
        ),
    ]
