# Generated by Django 4.1.3 on 2022-12-22 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("b", "business"), ("p", "personal")], max_length=1
                    ),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "driver_profile_type",
                    models.CharField(
                        choices=[("f", "full"), ("c", "council")], max_length=1
                    ),
                ),
                ("stripe_customer_id", models.CharField(max_length=100)),
                ("stripe_setup_intent_active", models.BooleanField(default=False)),
                ("credit_account", models.BooleanField(default=False)),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "db_table": "billing_account",
            },
        ),
        migrations.CreateModel(
            name="BillingAccountMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(default=0)),
                ("can_make_bookings", models.BooleanField(default=False)),
                (
                    "billing_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.billingaccount",
                    ),
                ),
            ],
            options={
                "db_table": "billing_account_member",
            },
        ),
    ]
