# Generated by Django 4.1.3 on 2022-12-05 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("b", "business"), ("p", "personal")], max_length=1
                    ),
                ),
                ("account_name", models.CharField(max_length=100, null=True)),
                (
                    "driver_profile_type",
                    models.CharField(
                        choices=[("f", "full"), ("c", "council")], max_length=1
                    ),
                ),
                ("stripe_customer_id", models.CharField(max_length=100)),
                ("stripe_setup_intent_active", models.BooleanField(default=False)),
                ("credit_account", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BillingAccountMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(default=0)),
                ("can_make_bookings", models.BooleanField(default=False)),
                (
                    "billing_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.billingaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="members",
            field=models.ManyToManyField(
                related_name="billing_accounts",
                through="billing.BillingAccountMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_billing_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
