# Generated by Django 4.1.4 on 2023-01-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BillingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("b", "business"), ("p", "personal")], max_length=1
                    ),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "driver_profile_type",
                    models.CharField(
                        choices=[("f", "full"), ("c", "council")], max_length=1
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("stripe_setup_intent_active", models.BooleanField(default=False)),
                ("credit_account", models.BooleanField(default=False)),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "business_address_line_1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_address_line_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_address_line_3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_address_line_4",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_postcode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_tax_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={
                "db_table": "billing_account",
            },
        ),
        migrations.CreateModel(
            name="BillingAccountMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("can_make_bookings", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "billing_account_member",
            },
        ),
        migrations.CreateModel(
            name="BillingAccountMemberInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_make_bookings", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=254)),
                ("secret", models.UUIDField()),
                ("created_at", models.DateTimeField()),
                (
                    "billing_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="billing.billingaccount",
                    ),
                ),
            ],
            options={
                "db_table": "billing_account_member_invitation",
            },
        ),
    ]
