# Generated by Django 4.1.4 on 2023-01-01 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaccountmemberinvitation",
            name="inviting_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="billingaccountmember",
            name="billing_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="billing.billingaccount"
            ),
        ),
        migrations.AddField(
            model_name="billingaccountmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="members",
            field=models.ManyToManyField(
                related_name="billing_accounts",
                through="billing.BillingAccountMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billingaccount",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_billing_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="billingaccountmember",
            unique_together={("billing_account", "user")},
        ),
    ]
