# Generated by Django 4.1.3 on 2022-12-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaccount",
            name="approved_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
