# Generated by Django 4.1.5 on 2023-01-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingaccount",
            name="driver_profile_type",
            field=models.CharField(
                choices=[("f", "full"), ("e", "external")], max_length=1
            ),
        ),
    ]
