# Generated by Django 5.0.11 on 2025-01-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_billingaccount_driver_profile_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaccount",
            name="business_purchase_order",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
