# Generated by Django 4.1.3 on 2022-12-30 19:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0004_billingaccountmemberinvitation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="billingaccountmember",
            unique_together={("billing_account", "user")},
        ),
    ]
