# Generated by Django 4.1.3 on 2022-12-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_alter_billingaccountmember_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billingaccountmemberinvitation",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="billingaccountmember",
            name="deleted_at",
        ),
    ]
