# Generated by Django 5.0.9 on 2025-01-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_billingaccount_business_purchase_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingaccount",
            name="business_purchase_order",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
