[pytest]
DJANGO_SETTINGS_MODULE = carshare.settings
testpaths =
    billing/tests.py
    bookings/tests.py
    users/tests.py
    drivers/tests.py
    backoffice/tests.py
    public/tests.py
    securemedia/tests.py
addopts = --cov=. --cov-report=term-missing --cov-fail-under=50
