# Generated by Django 4.1.4 on 2023-01-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("approved_to_drive", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "driver_profile",
            },
        ),
        migrations.CreateModel(
            name="FullDriverProfile",
            fields=[
                (
                    "driverprofile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="drivers.driverprofile",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "address_line_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("postcode", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "licence_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "licence_place_of_issue",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("licence_issue_date", models.DateField(blank=True, null=True)),
                ("licence_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "licence_front",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                (
                    "licence_back",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                (
                    "licence_selfie",
                    models.ImageField(
                        blank=True, null=True, upload_to="drivers/profiles/selfies"
                    ),
                ),
                (
                    "licence_check_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "approved_full_name",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (True, "Approve"),
                            (False, "Reject"),
                            ("", "Unchecked"),
                        ],
                        default="",
                        null=True,
                    ),
                ),
                (
                    "approved_address",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (True, "Approve"),
                            (False, "Reject"),
                            ("", "Unchecked"),
                        ],
                        default="",
                        null=True,
                    ),
                ),
                (
                    "approved_date_of_birth",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (True, "Approve"),
                            (False, "Reject"),
                            ("", "Unchecked"),
                        ],
                        default="",
                        null=True,
                    ),
                ),
                (
                    "approved_licence_number",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (True, "Approve"),
                            (False, "Reject"),
                            ("", "Unchecked"),
                        ],
                        default="",
                        null=True,
                    ),
                ),
                (
                    "approved_licence_place_of_issue",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (True, "Approve"),
                            (False, "Reject"),
                            ("", "Unchecked"),
                        ],
                        default="",
                        null=True,
                    ),
                ),
                (
                    "approved_licence_issue_date",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (True, "Approve"),
                            (False, "Reject"),
                            ("", "Unchecked"),
                        ],
                        default="",
                        null=True,
                    ),
                ),
                (
                    "approved_licence_expiry_date",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (True, "Approve"),
                            (False, "Reject"),
                            ("", "Unchecked"),
                        ],
                        default="",
                        null=True,
                    ),
                ),
                (
                    "approved_licence_front",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (True, "Approve"),
                            (False, "Reject"),
                            ("", "Unchecked"),
                        ],
                        default="",
                        null=True,
                    ),
                ),
                (
                    "approved_licence_back",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (True, "Approve"),
                            (False, "Reject"),
                            ("", "Unchecked"),
                        ],
                        default="",
                        null=True,
                    ),
                ),
                (
                    "approved_licence_selfie",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (True, "Approve"),
                            (False, "Reject"),
                            ("", "Unchecked"),
                        ],
                        default="",
                        null=True,
                    ),
                ),
                (
                    "approved_driving_record",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (True, "Approve"),
                            (False, "Reject"),
                            ("", "Unchecked"),
                        ],
                        default="",
                        null=True,
                    ),
                ),
                ("dvla_summary", models.FileField(blank=True, null=True, upload_to="")),
            ],
            options={
                "db_table": "full_driver_profile",
            },
            bases=("drivers.driverprofile",),
        ),
    ]
