# Generated by Django 4.0 on 2021-12-29 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_billingaccount_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(max_length=255)),
                ('address_line_3', models.CharField(max_length=255)),
                ('address_line_4', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('licence_number', models.CharField(max_length=255)),
                ('licence_place_of_issue', models.CharField(max_length=255)),
                ('licence_issue_date', models.DateField()),
                ('licence_expiry_date', models.DateField()),
                ('licence_front', models.ImageField(upload_to='')),
                ('licence_back', models.ImageField(upload_to='')),
                ('licence_selfie', models.ImageField(upload_to='')),
                ('licence_check_code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('approved_full_name', models.BooleanField(null=True)),
                ('approved_address', models.BooleanField(null=True)),
                ('approved_date_of_birth', models.BooleanField(null=True)),
                ('approved_licence_number', models.BooleanField(null=True)),
                ('approved_licence_place_of_issue', models.BooleanField(null=True)),
                ('approved_licence_issue_date', models.BooleanField(null=True)),
                ('approved_licence_expiry_date', models.BooleanField(null=True)),
                ('approved_licence_front', models.BooleanField(null=True)),
                ('approved_licence_back', models.BooleanField(null=True)),
                ('approved_licence_selfie', models.BooleanField(null=True)),
                ('approved_driving_record', models.BooleanField(null=True)),
                ('dvla_summary', models.FileField(upload_to='')),
                ('approved_to_drive', models.BooleanField(null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_profiles', to='users.user')),
            ],
        ),
    ]
