# Generated by Django 4.1.3 on 2022-12-06 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                ("expires_at", models.DateTimeField(null=True)),
                ("approved_to_drive", models.BooleanField(null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="driver_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="FullDriverProfile",
            fields=[
                (
                    "driverprofile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="drivers.driverprofile",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, null=True)),
                ("address_line_1", models.CharField(max_length=255, null=True)),
                ("address_line_2", models.CharField(max_length=255, null=True)),
                ("address_line_3", models.CharField(max_length=255, null=True)),
                ("address_line_4", models.CharField(max_length=255, null=True)),
                ("postcode", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
                ("date_of_birth", models.DateField(null=True)),
                ("licence_number", models.CharField(max_length=255, null=True)),
                ("licence_place_of_issue", models.CharField(max_length=255, null=True)),
                ("licence_issue_date", models.DateField(null=True)),
                ("licence_expiry_date", models.DateField(null=True)),
                ("licence_front", models.ImageField(null=True, upload_to="")),
                ("licence_back", models.ImageField(null=True, upload_to="")),
                (
                    "licence_selfie",
                    models.ImageField(null=True, upload_to="drivers/profiles/selfies"),
                ),
                ("licence_check_code", models.CharField(max_length=50, null=True)),
                ("approved_full_name", models.BooleanField(null=True)),
                ("approved_address", models.BooleanField(null=True)),
                ("approved_date_of_birth", models.BooleanField(null=True)),
                ("approved_licence_number", models.BooleanField(null=True)),
                ("approved_licence_place_of_issue", models.BooleanField(null=True)),
                ("approved_licence_issue_date", models.BooleanField(null=True)),
                ("approved_licence_expiry_date", models.BooleanField(null=True)),
                ("approved_licence_front", models.BooleanField(null=True)),
                ("approved_licence_back", models.BooleanField(null=True)),
                ("approved_licence_selfie", models.BooleanField(null=True)),
                ("approved_driving_record", models.BooleanField(null=True)),
                ("dvla_summary", models.FileField(upload_to="")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("drivers.driverprofile",),
        ),
    ]
