# Generated by Django 4.0 on 2022-01-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_billingaccount_account_name"),
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="address_line_1",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="address_line_2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="address_line_3",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="address_line_4",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="approved_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="full_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="licence_back",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="licence_check_code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="licence_expiry_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="licence_front",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="licence_issue_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="licence_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="licence_place_of_issue",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="licence_selfie",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="postcode",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
