# Generated by Django 4.1.3 on 2022-12-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="approved_address",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Approve"), (False, "Reject"), ("", "Unchecked")],
                default="",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="approved_date_of_birth",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Approve"), (False, "Reject"), ("", "Unchecked")],
                default="",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="approved_driving_record",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Approve"), (False, "Reject"), ("", "Unchecked")],
                default="",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="approved_full_name",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Approve"), (False, "Reject"), ("", "Unchecked")],
                default="",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="approved_licence_back",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Approve"), (False, "Reject"), ("", "Unchecked")],
                default="",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="approved_licence_expiry_date",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Approve"), (False, "Reject"), ("", "Unchecked")],
                default="",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="approved_licence_front",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Approve"), (False, "Reject"), ("", "Unchecked")],
                default="",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="approved_licence_issue_date",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Approve"), (False, "Reject"), ("", "Unchecked")],
                default="",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="approved_licence_number",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Approve"), (False, "Reject"), ("", "Unchecked")],
                default="",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="approved_licence_place_of_issue",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Approve"), (False, "Reject"), ("", "Unchecked")],
                default="",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="approved_licence_selfie",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Approve"), (False, "Reject"), ("", "Unchecked")],
                default="",
                null=True,
            ),
        ),
    ]
