# Generated by Django 4.1.4 on 2023-01-01 21:04

from django.db import migrations, models
import drivers.models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="dvla_summary",
            field=models.FileField(
                blank=True, null=True, upload_to=drivers.models.dvla_summary_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="licence_back",
            field=models.ImageField(
                blank=True, null=True, upload_to=drivers.models.licence_back_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="licence_front",
            field=models.ImageField(
                blank=True, null=True, upload_to=drivers.models.licence_front_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="licence_selfie",
            field=models.ImageField(
                blank=True, null=True, upload_to=drivers.models.licence_selfie_upload_to
            ),
        ),
    ]
