# Generated by Django 4.0 on 2022-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_alter_driverprofile_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="submitted_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="licence_selfie",
            field=models.ImageField(null=True, upload_to="drivers/profiles/selfies"),
        ),
    ]
