# Generated by Django 4.1.5 on 2023-01-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "drivers",
            "0004_remove_fulldriverprofile_approved_licence_place_of_issue_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalDriverProfile",
            fields=[
                (
                    "driverprofile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="drivers.driverprofile",
                    ),
                ),
                ("commentary", models.TextField(blank=True)),
            ],
            options={
                "db_table": "external_driver_profile",
            },
            bases=("drivers.driverprofile",),
        ),
    ]
