# Generated by Django 5.0.11 on 2025-03-12 11:27

import drivers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0005_externaldriverprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="licence_back",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=drivers.models.licence_back_upload_to,
                validators=[drivers.models.validate_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="licence_front",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=drivers.models.licence_front_upload_to,
                validators=[drivers.models.validate_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="licence_selfie",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=drivers.models.licence_selfie_upload_to,
                validators=[drivers.models.validate_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="fulldriverprofile",
            name="proof_of_address",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=drivers.models.proof_of_address_upload_to,
                validators=[drivers.models.validate_file_extension],
            ),
        ),
    ]
