# Generated by Django 4.1.4 on 2023-01-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "bay",
            },
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.BigIntegerField()),
                ("secret", models.UUIDField()),
                ("locked", models.BooleanField(blank=True, default=True)),
            ],
            options={
                "verbose_name_plural": "boxes",
                "db_table": "box",
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("enabled", models.BooleanField(default=True)),
                ("operator", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "card",
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "station",
            },
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=36)),
            ],
            options={
                "db_table": "vehicle_type",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_model", models.CharField(max_length=100)),
                ("registration", models.CharField(max_length=8)),
                ("vin", models.CharField(max_length=100)),
                ("firmware_model", models.CharField(max_length=255)),
                ("operator_cards_etag", models.IntegerField(default=0)),
                (
                    "bay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hardware.bay"
                    ),
                ),
                (
                    "box",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="hardware.box"
                    ),
                ),
                ("operator_cards", models.ManyToManyField(to="hardware.card")),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hardware.vehicletype",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle",
            },
        ),
    ]
