# Generated by Django 4.1.4 on 2023-01-01 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hardware", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="current_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="unlocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="hardware.card",
            ),
        ),
        migrations.AddField(
            model_name="bay",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="hardware.station"
            ),
        ),
    ]
