# Generated by Django 4.1.4 on 2023-01-02 16:26

from django.db import migrations, models
import hardware.models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=hardware.models.vehicle_picture_upload_to,
            ),
        ),
    ]
