# Generated by Django 4.0.1 on 2022-03-10 14:45
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0003_station_bay_vehicle_bay"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="secret",
            field=models.UUIDField(default=uuid.uuid4()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="box",
            name="serial",
            field=models.BigIntegerField(),
        ),
    ]
