# Generated by Django 4.1.4 on 2023-01-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0003_vehicle_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="location",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicletype",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
