# Generated by Django 4.0.1 on 2022-03-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0004_box_secret_alter_box_serial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="operator_cards_etag",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="box",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="hardware.box"
            ),
        ),
    ]
