# Generated by Django 5.0.11 on 2025-02-02 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0008_alter_boxaction_payload_alter_boxaction_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Telemetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("odometer_miles", models.IntegerField(null=True)),
                ("doors_locked", models.BooleanField(null=True)),
                ("aux_battery_voltage", models.FloatField(null=True)),
                ("ibutton_id", models.CharField(max_length=16, null=True)),
                ("box_uptime_s", models.IntegerField(null=True)),
                ("box_free_heap_bytes", models.IntegerField(null=True)),
                ("soc_percent", models.IntegerField(null=True)),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hardware.box"
                    ),
                ),
            ],
            options={
                "db_table": "telemetry",
            },
        ),
    ]
