# Generated by Django 4.1.3 on 2022-12-22 21:59

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("cancelled", "cancelled"),
                            ("active", "active"),
                            ("inactive", "inactive"),
                            ("late", "late"),
                            ("ended", "ended"),
                            ("billed", "billed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "reservation_time",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                (
                    "block_time",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "booking",
            },
        ),
    ]
