# Generated by Django 4.0.1 on 2022-02-13 16:26

from django.conf import settings
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hardware", "0002_alter_box_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cancelled", models.BooleanField(default=False)),
                (
                    "reservation_time",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                (
                    "block_time",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="hardware.vehicle",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("cancelled", False)),
                expressions=(("block_time", "&&"), ("vehicle_id", "=")),
                name="prevent_overlaps",
            ),
        ),
    ]
