# Generated by Django 4.0.1 on 2022-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="cancelled",
        ),
        migrations.AddField(
            model_name="booking",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("cancelled", "cancelled"),
                    ("active", "active"),
                    ("late", "late"),
                    ("ended", "ended"),
                    ("billed", "billed"),
                ],
                default="pending",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
