# Generated by Django 4.0.1 on 2022-06-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_remove_booking_cancelled_booking_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="actual_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="actual_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("cancelled", "cancelled"),
                    ("active", "active"),
                    ("inactive", "inactive"),
                    ("late", "late"),
                    ("ended", "ended"),
                    ("billed", "billed"),
                ],
                default="active",
                max_length=16,
            ),
        ),
    ]
