# Generated by Django 5.0.11 on 2025-03-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reason",
            field=models.CharField(
                choices=[
                    ("user booking", "user booking"),
                    ("maintenance", "maintenance"),
                    ("retired", "retired"),
                ],
                default="user booking",
                max_length=12,
            ),
        ),
    ]
