# Generated by Django 4.1.3 on 2022-12-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_actual_end_time_booking_actual_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("cancelled", "cancelled"),
                    ("active", "active"),
                    ("inactive", "inactive"),
                    ("late", "late"),
                    ("ended", "ended"),
                    ("billed", "billed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
