# Generated by Django 4.1.3 on 2022-12-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_billing_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="stripe_invoice_item_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
